---
title: "Transcriptions of sounds"
author: "Pierce Edmiston"
output:
  html_document:
    theme: flatly
---

```{r config, echo = FALSE, message = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  fig.path = 'figs/'
)

library(ggplot2)
library(dplyr)
library(magrittr)

library(wordsintransition)
data("imitations")
data("transcriptions")

imitations %<>%
  filter(game_name == "words-in-transition")

transcriptions %<>%
  filter(is_catch_trial == 0) %>%
  # label the generation of the imitations being transcribed
  left_join(imitations[, c("imitation_id", "generation")])
  

base <- ggplot() +
  theme_minimal()

scale_x_generation <- scale_x_continuous(breaks = 0:8)
```

# Number of sound effects and imitations

```{r num-imitations}
hist <- base +
  geom_histogram(aes(x = generation), binwidth = 1,
                 color = "black", fill = "white", alpha = 0.6) +
  geom_text(aes(x = generation, label = ..count..),
            stat = "bin", binwidth = 1, vjust = 1.6) +
  scale_x_generation

hist %+% imitations
```

# Number of sound effects and imitations that have been transcribed

```{r num-imitations-transcribed}
transcribed_imitations <- imitations %>%
  filter(imitation_id %in% transcriptions$imitation_id)

(hist %+% transcribed_imitations) +
  ggtitle("Number of transcribed imitations")

hist_no_labels <- hist
hist_no_labels$layers[[2]] <- NULL

(hist_no_labels %+% transcribed_imitations) +
  geom_histogram(aes(x = generation), data = imitations,
                 binwidth = 1, fill = "black", alpha = 0.2) +
  ggtitle("Proportion of imitations transcribed")
```

# Number of transcriptions for each transcribed sound effect and imitation

```{r num-transcriptions-per-imitation}
decr_imitation_ids <- count(transcriptions, imitation_id) %>%
  arrange(-n) %>% 
  .$imitation_id
transcriptions$imitation_id_decr <- factor(transcriptions$imitation_id,
                                           levels = decr_imitation_ids)

(base %+% transcriptions) +
  geom_bar(aes(x = imitation_id_decr, fill = generation), stat = "count",
           width = 1.0, color = "white", alpha = 0.8) +
  scale_x_discrete("Imitation ID") +
  ggtitle("Transcriptions per sound")
```