---
title: "Methods"
author: "Pierce Edmiston"
output:
  html_document:
    theme: flatly
    toc: true
---

## Determining seeds

We needed 4 different categories of sounds, and 4 exemplars of each category,
resulting in a total of 16 seed sounds. Our desire was to have approximately
the same amount of variation within each category. For example, we didn't want
any one of the sounds in each category to stand out in comparison to the others.

To do this, we started with 6 categories of sounds, and 6 exemplars of each
category. Then we had norming participants to listen to each of the sounds
in a category and pick the one that was the most different. After an initial
round of norming, we removed the most egregious outliers, and ran another
round of norming, this time with 5 categories of sounds and 5 exemplars in
each category. Again participants picked the outlier sound.

## Collecting imitations

## Match to seed ratings from imitations

## Obtaining transcriptions

## Match to seed ratings from transcriptions