# Matching imitations back to seeds

To measure the fidelity of the imitations, we had participants listen to each
imitation and attempt to match it to it's source--the seed sound.

```{r, include=FALSE}
library(dplyr)
library(ggplot2)
library(scales)
library(grid)
library(tidyr)
library(lme4)
library(AICcmodavg)
library(pander)
library(png)

source("R/img.R")

global_theme <- theme_minimal() +
  theme(axis.ticks = element_blank())

colors <- RColorBrewer::brewer.pal(4, "Set2")
names(colors) <- c("blue", "orange", "green", "pink")
question_type_colors <- unname(colors[c("green", "blue", "orange")])


# colors
between_color <- colors[["green"]]
within_color <- colors[["blue"]]

# ggplot theme
distractor_labels <- c("True seed", "Category match", "Specific match")
distractor_colors <- question_type_colors

scale_y_accuracy <- scale_y_continuous(
  "Guess the seed accuracy",
  labels = percent,
  breaks = seq(0, 1, by = 0.25)
)
scale_x_generation <- scale_x_continuous(
  "Generation",
  breaks = 1:12
)
scale_x_generation_1 <- scale_x_continuous(
  "Generation",
  breaks = 0:11,
  labels = 1:12
)
scale_x_distractors <- scale_x_discrete(
  "",
  labels = distractor_labels
)
scale_fill_distractors <- scale_fill_manual(
  "",
  values = distractor_colors
)
scale_fill_categories <- scale_fill_manual(
  "",
  values = unname(colors)
)
scale_color_distractors <- scale_color_manual(
  "",
  values = distractor_colors,
  labels = distractor_labels
)

chance_line <- geom_hline(yintercept = 0.25, lty = 2, alpha = 0.4, size = 1)
chance_label <- annotate("text", x = 10, y = 0.26, label = "chance",
                         size = 7, vjust = -0.1, fontface = "italic", alpha = 0.4)

distractor_xlim <- c(-0.2, 7.2)
distractor_coords <- coord_cartesian(
  xlim = distractor_xlim,
  ylim = c(-0.02, 1.02)
)
distractor_diff_coords <- coord_cartesian(
  xlim = distractor_xlim,
  ylim = c(-0.02, 0.8)
)

library(wordsintransition)
data("imitation_matches")
read_wordsintransition_chunks()

survey_map <- data_frame(
  survey_type = c("between", "same", "within"),
  # Treatment contrasts
  same_v_between = c(1, 0, 0),
  same_v_within = c(0, 0, 1)
)

imitation_matches <- imitation_matches %>%
  filter(question_type != "catch_trial") %>%
  mutate(generation_1 = generation - 1) %>%
  left_join(survey_map)


```

## Methods

### Question types

<!-- WARNING: Can't hide graphviz output.
```{r true-seed, engine = "dot", results = "hide", fig.show = "hide"}
```
-->

<!-- WARNING: Can't hide graphviz output.
```{r category-match, engine = "dot", results = "hide", fig.show = "hide"}
```
-->

<!-- WARNING: Can't hide graphviz output.
```{r specific-match, engine = "dot", results = "hide", fig.show = "hide"}
```
-->

```{r 4-question-types, fig.width=4, fig.height=4, results="hide"}
read_chunk_fig <- function(label, draw = TRUE, ...) {
  label %>%
    paste0("-1.png") %>%
    file.path("figs", .) %>%
    readPNG() %>%
    rasterGrob(...) %T>%
    { if(draw) grid.draw(.) }
}

grid.newpage()
read_chunk_fig("true-seed", y = 0.8, width = 0.9)
read_chunk_fig("category-match", y = 0.5, width = 0.9)
read_chunk_fig("specific-match", y = 0.2, width = 0.9)
```

### Procedure

```{r 3-match-imitations-gui, fig.width=3, fig.height=3}
img("match-imitations-gui")
```

## Results

```{r 4-match-imitations-mod, echo=1}
match_imitations_mod <- glmer(
  is_correct ~ generation_1 * (same_v_between + same_v_within) + (generation_1|chain_name/seed_id),
  family = "binomial", data = imitation_matches)

match_imitations_preds <- expand.grid(
  generation_1 = unique(imitation_matches$generation_1),
  survey_type = c("between", "same", "within"),
  stringsAsFactors = FALSE
) %>% left_join(survey_map) %>%
  mutate(
    generation = generation_1 + 1,
    generation_label = paste("Generation", generation)
  ) %>%
  cbind(., predictSE(match_imitations_mod, ., se = TRUE)) %>%
  rename(is_correct = fit, se = se.fit)
```

```{r 4-match-imitations-results, results="asis"}
broom::tidy(match_imitations_mod, effects = "fixed") %>%
  knitr::kable(digits = 2)
```

```{r 4-match-imitations}
gg_match_to_seed <- ggplot(imitation_matches, aes(x = generation_1, y = is_correct)) +
  geom_smooth(aes(ymin = is_correct - se, ymax = is_correct + se, color = survey_type),
              stat = "identity", data = match_imitations_preds,
              size = 1.0) +
  scale_x_generation_1 +
  scale_y_continuous("Accuracy", breaks = seq(0, 1, by = 0.15), labels = percent) +
  scale_color_distractors +
  chance_line +
  coord_cartesian(xlim = c(-0.2, 7.2), ylim = c(0.15, 0.75)) +
  global_theme +
  theme(legend.position = c(0.8, 0.85))
gg_match_to_seed
```
