--- 
title: "Creating words from iterated vocal imitation"
author: "Pierce Edmiston, Marcus Perlman, and Gary Lupyan"
output:
  bookdown::gitbook:
    toc_depth: 1
documentclass: book
bibliography: [packages.bib]
biblio-style: apalike
link-citations: yes
---

# Abstract {-}

```{r include=FALSE}
# create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')

knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  cache.path = ".cache/",
  fig.path = "figs/",
  results = "hide"
)
```

New words are constantly being invented, yet we have never witnessed the emergence of spoken words in the absence of prior convention. We report the results of a large-scale (n=XXXX) experiment designed to investigate whether spoken words can emerge solely from the process of repeated imitation beginning with environmental sounds. Participants played an online version of the children’s game “Telephone” wherein a message is passed from person to person with the goal of keeping it unchanged. The first generation of players heard familiar environmental sounds (e.g., glass breaking, water splashing) and had to imitate the sounds. The next generation imitated the imitations, and so on for a maximum of 8 generations (XXXX imitators). We subsequently assessed whether the imitations (1) became more stable and word-like, (2) retained a resemblance to the original environmental sound as measured by people’s ability to guess the meanings in the absence of learning, and (3) the extent to which the imitations from different generations were suitable as verbal category labels. The results showed that vocal imitations became progressively more word-like as measured by acoustic similarity and agreement of orthographic transcriptions, that even after 10 generations they could be matched above chance to the environmental sound that motivated them, and that imitations from later generations were more effective as learned category labels. These results show how repeated imitation, even in the absence of an explicit intention to communicate, can create progressively more word-like forms while retaining a semblance of iconicity.

# Introduction {-}

Over the ages, people have pondered the origins of language and especially the words that compose them (Plato, Bible). Where do words come from? Some theories of language evolution hypothesize that vocal imitation played an important role in generating the first words in the evolution of spoken languages (Brown, Black & Horowitz, 1955; Imai & Kita, 2014; Perlman, Dale, & Lupyan, 2015). In this study, we investigate the formation of onomatopoeic words – imitative words that resemble the sounds to which they refer.
 
Onomatopoeic words appear to be a universal lexical category found across the world’s languages (Dingemanse, 2012; others). Languages all have conventional words for animal vocalizations and other environmental sounds. Such words appear to be especially prominent for very young language learners (Laing, Vihman, & Keren-Portnoy, 2016; Tardif, Fletcher, Liang, Zhang, Kaciroti, & Marchman, 2008).
 
In some cases, words that begin as imitations of sounds become fully lexicalized and integrated into the broader linguistic system, when they behave like more “ordinary” words that can undergo typical morphological processes. Dingemanse and Akita (2016) show this on variable instance-by-instance basis rather than a monotonic historical process towards integration. Rhodes (1994) observed that onomatopoeic words exist along a continuum from “wild” to “tame” in which wild words have a more imitative phonology whereas tame words take on more standard phonology of other English words. In English, words like crack or the recently adapted ping.
 
Vocal imitation experiments by Lemaitre et al. (2016), Lemaitre & Rocchesso (2014), Lemaitre et al (2011), Lemaitre et al (2016).
 
In addition to iconic words for sounds, many languages have a semantically broader system of ideophones. Dingemanse et al. (2016) found that naïve listeners were better than chance at guessing the meanings of ideophones (sampled from five different languages) from five different semantic categories: color/visual, motion, shape, sound, and texture, but sound words were guessed more accurately than the rest. Experiments suggest that iconic vocalizations for non-sound concepts can also become more word-like over repeated use (Perlman, Dale, & Lupyan, 2015).
 
Discussion
We show that repeated imitation of an originally imitative vocalization works to integrate it into the ambient language. Consequently, it becomes more abstract in its resemblance to its initial source sound, but maintains some resemblance to the more abstract category of sounds. The vocalizations become more learnable as linguistic labels for categories.
 
Repeated drawings from memory (without delay) result in drawings that become more conventional, moving towards cultural attractors such as letters (Tamariz & Kirby, 2014). Also Bartlett.
 
More broadly, imitative words are hypothesized to play an important role in the evolution of language (Brown, Black & Horowitz, 1955; Imai & Kita, 2014; Perlman, Dale, & Lupyan, 2015).